# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'developer'
      MYSQL_PASSWORD: 'Developer123'
      MYSQL_ROOT_PASSWORD: 'Developer123'
    ports:
      - '9898:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - db-mysql:/var/lib/mysql


  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
# Names our volume
volumes:
  db-mysql: